config/routes.rb
WebsocketsApp::Application.routes.draw do
  resources :messages
  

  

end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

	def index
		@messages = Message.all
		@message = Message.new
	end

	def new
		@message = Message.new
	end

	def create
		@message = Message.create(params[:message].permit(:name, :message))
		WebsocketRails[:messages].trigger 'yo', @message
		
		#example unobtrusive javascript 
		# respond_to do |format|
		# 	@message.save
		# 	format.html { redirect_to @message, notice:"Good job"}
		# 	format.js { }
		# 	format.json { render json: @message, status: :created, location: @message }
		# end
		
		redirect_to messages_path #Message 
	end


	def show
		@message = Message.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WebsocketsApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>


<script id="message_feed_template" type="text/x-handlebars-template">
<p>
	{{name}}
	<a href="/messages/{{id}}">
		{{message}}
	</a>
</p>
</script> 

app/views/messages/index.html.erb
<h3>Shit just got real(time)</h3>

	<%= form_for @message do |m| %>
	  	<p>
		    <%= m.label :name %><br>
		    <%= m.text_field :name, placeholder: 'User name' %>
		</p>
		    <%= m.label :message %><br>
		    <%= m.text_area :message, placeholder: 'Message content' %><br />
	  		<%= m.submit "Send message" %>
	  	</p>
	    	
	<% end %>


	<h4>Message history</h4>
		<div id="message_feed">
				<% @messages.each do |m| %>
					<p>
						<%= m.name %>
						<%= link_to m.message, message_path(m) %>	
					</p>
				<% end %>
		</div>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= form_for @message do |m| %>
  <p>
    <%= m.label :name %><br>
    <%= m.text_field :name, placeholder: 'User name' %>
  </p>
 
  <p>
    <%= m.label :message %><br>
    <%= m.text_area :message, placeholder: 'Message content' %>
  </p>
 
  <p>
    <%= m.submit "Send message" %>
  </p>

  <% end %>

app/views/messages/show.html.erb
<strong><%= @message.name %></strong> 
<span> ---- </span>
  <%= @message.message %>


  